### ISSUE TITLE
Cannot generate dataset

### ISSUE THREAD

**Issue by Tangetb** [ros-industrial/easy_perception_deployment#26]
`Creating dataset: ../data/datasets/custom_dataset/train_dataset
Traceback (most recent call last):
  File "dataset/labelme2coco.py", line 182, in <module>
    main()
  File "dataset/labelme2coco.py", line 91, in main
    assert class_name == '__ignore__'
AssertionError
Creating dataset: ../data/datasets/custom_dataset/val_dataset
Traceback (most recent call last):
  File "dataset/labelme2coco.py", line 182, in <module>
    main()
  File "dataset/labelme2coco.py", line 91, in main
    assert class_name == '__ignore__'
AssertionError
`
Have this error upon generating the dataset. I went to check the dataset file, the train_dataset and val_dataset have empty Jpeg folder and no annotation file is created

**Comment by cardboardcode** [comment]
Hi @Tangetb, 

It seems the `.txt` **label list file** you have is missing the necessary `__ignore__` class name. 

Please refer to [this section of the documentation](https://easy-perception-deployment.readthedocs.io/en/latest/guide/custom_p2p3_train.html#create-custom-label-list) for further clarification.

Your `.txt` label list file should look like this:
```txt
__ignore__
_background_
object_class_1_name
object_class_2_name
```
