### ISSUE TITLE
Issue in deploying custom ONNX Model

### ISSUE THREAD

**Issue by Prabhakaran-Gokul** [ros-industrial/easy_perception_deployment#45]
Hi all, 

I trained my own custom dataset with YOLOv5s pre-trained model. I want to deploy my model in this package so I followed the instructions given in the [documentation](https://epd-docs.readthedocs.io/en/latest/guide/custom_deploy.html). Initially my model had an incompatible model input shape hence, I retrained my model with the required input shape of 224. 

I exported my model to .onnx format using this guide (https://github.com/ultralytics/yolov5/issues/251) and made sure that the model performs as expected with the inference code given by YOLOv5 on images with input shape 224. I also created a [custom_yolov5_classes.txt](https://github.com/ros-industrial/easy_perception_deployment/files/8939059/custom_yolov5_classes.txt)
file under the label_list folder.

However, no message is published to the /processor/output topic. The Showimage window is also not responding. Here is my terminal output: 
![termial_output_edp](https://user-images.githubusercontent.com/50551629/174565975-2b67e2d6-0811-4266-805c-40bd57cbaf25.png)

I am able to run the given models(FasterRCNN, MaskRCNN) without any issues. Hope to get your advice on this!

**Comment by cardboardcode** [comment]
Hi @Prabhakaran-Gokul, may I clarify if you are using EPD docker which is activated when using the EPD Graphical User Interface?

If so, there is **a quick fix** for this since it may narrow down the source of error to the use of docker.

**Comment by cardboardcode** [comment]
Closing due to staleness for more than 30 days. Feel free to reopen if there is still interest in resolving this issue.
